# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hakkindapg.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hakkinda(object):
    def setupUi(self, hakkinda):
        hakkinda.setObjectName("hakkinda")
        hakkinda.resize(400, 300)
        hakkinda.setStyleSheet("QWidget#hakkinda{\n"
"background-color: qlineargradient(spread:pad, x1:0.144, y1:0.188, x2:1, y2:1, stop:0 rgba(147, 183, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);}")
        self.label_2 = QtWidgets.QLabel(hakkinda)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 341, 31))
        self.label_2.setStyleSheet("color:rgb(24, 93, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(hakkinda)
        self.label_3.setGeometry(QtCore.QRect(80, 100, 231, 31))
        self.label_3.setStyleSheet("color:rgb(24, 93, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(hakkinda)
        QtCore.QMetaObject.connectSlotsByName(hakkinda)

    def retranslateUi(self, hakkinda):
        _translate = QtCore.QCoreApplication.translate
        hakkinda.setWindowTitle(_translate("hakkinda", "Hakkında"))
        self.label_2.setText(_translate("hakkinda", "Ali AKSAKAL tarafından oluşturulmuştur.           "))
        self.label_3.setText(_translate("hakkinda", "Her Hakkı Saklıdır.(2023)"))
