# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginpage(object):
    def setupUi(self, loginpage):
        loginpage.setObjectName("loginpage")
        loginpage.resize(400, 300)
        loginpage.setStyleSheet("QLabel#label_3{\n"
"background-color: qlineargradient(spread:pad, x1:0.144, y1:0.188, x2:1, y2:1, stop:0 rgba(147, 183, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);}")
        self.label_3 = QtWidgets.QLabel(loginpage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 411, 301))
        self.label_3.setStyleSheet("QLabel#label_3{\n"
"background-color: qlineargradient(spread:pad, x1:0.144, y1:0.188, x2:1, y2:1, stop:0 rgba(147, 183, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(loginpage)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(24, 93, 255)")
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(loginpage)
        self.widget.setGeometry(QtCore.QRect(50, 90, 171, 164))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(24, 93, 255)")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_kullaniciadi = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_kullaniciadi.setFont(font)
        self.lineEdit_kullaniciadi.setText("")
        self.lineEdit_kullaniciadi.setObjectName("lineEdit_kullaniciadi")
        self.verticalLayout.addWidget(self.lineEdit_kullaniciadi)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(24, 93, 255)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_sifre.setFont(font)
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.verticalLayout.addWidget(self.lineEdit_sifre)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(24, 93, 255)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.pushButton_giris = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_giris.setFont(font)
        self.pushButton_giris.setStyleSheet("color:rgb(24, 93, 255);\n"
"background-color: rgba(153, 186, 221, 47);\n"
"")
        self.pushButton_giris.setObjectName("pushButton_giris")
        self.verticalLayout.addWidget(self.pushButton_giris)

        self.retranslateUi(loginpage)
        QtCore.QMetaObject.connectSlotsByName(loginpage)

    def retranslateUi(self, loginpage):
        _translate = QtCore.QCoreApplication.translate
        loginpage.setWindowTitle(_translate("loginpage", "Form"))
        self.label_5.setText(_translate("loginpage", "Giriş Yapmak İçin Kullanıcı Adı Ve Şifrenizi Giriniz"))
        self.label.setText(_translate("loginpage", "Kullanıcı Adı"))
        self.label_2.setText(_translate("loginpage", "Şifre"))
        self.pushButton_giris.setText(_translate("loginpage", "GİRİŞ"))
