# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerpage(object):
    def setupUi(self, registerpage):
        registerpage.setObjectName("registerpage")
        registerpage.resize(406, 301)
        self.label_3 = QtWidgets.QLabel(registerpage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 411, 301))
        self.label_3.setStyleSheet("QLabel#label_3{\n"
"background-color: qlineargradient(spread:pad, x1:0.144, y1:0.188, x2:1, y2:1, stop:0 rgba(147, 183, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(registerpage)
        self.widget.setGeometry(QtCore.QRect(50, 30, 168, 236))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelkullaniciadi = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelkullaniciadi.setFont(font)
        self.labelkullaniciadi.setStyleSheet("color:rgb(24, 93, 255)")
        self.labelkullaniciadi.setObjectName("labelkullaniciadi")
        self.verticalLayout.addWidget(self.labelkullaniciadi)
        self.lineEdit_kullaniciadi = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_kullaniciadi.setFont(font)
        self.lineEdit_kullaniciadi.setObjectName("lineEdit_kullaniciadi")
        self.verticalLayout.addWidget(self.lineEdit_kullaniciadi)
        self.labelsifre = QtWidgets.QLabel(self.widget)
        self.labelsifre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelsifre.setFont(font)
        self.labelsifre.setStyleSheet("color:rgb(24, 93, 255)")
        self.labelsifre.setObjectName("labelsifre")
        self.verticalLayout.addWidget(self.labelsifre)
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_sifre.setFont(font)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.verticalLayout.addWidget(self.lineEdit_sifre)
        self.labelmailadresi = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelmailadresi.setFont(font)
        self.labelmailadresi.setStyleSheet("color:rgb(24, 93, 255)")
        self.labelmailadresi.setObjectName("labelmailadresi")
        self.verticalLayout.addWidget(self.labelmailadresi)
        self.lineEdit_mailadresi = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_mailadresi.setFont(font)
        self.lineEdit_mailadresi.setObjectName("lineEdit_mailadresi")
        self.verticalLayout.addWidget(self.lineEdit_mailadresi)
        self.labelmailadresi_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelmailadresi_2.setFont(font)
        self.labelmailadresi_2.setText("")
        self.labelmailadresi_2.setObjectName("labelmailadresi_2")
        self.verticalLayout.addWidget(self.labelmailadresi_2)
        self.pushButton_kayit = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_kayit.setFont(font)
        self.pushButton_kayit.setStyleSheet("color:rgb(24, 93, 255);\n"
"background-color: rgba(153, 186, 221, 47);")
        self.pushButton_kayit.setObjectName("pushButton_kayit")
        self.verticalLayout.addWidget(self.pushButton_kayit)

        self.retranslateUi(registerpage)
        QtCore.QMetaObject.connectSlotsByName(registerpage)

    def retranslateUi(self, registerpage):
        _translate = QtCore.QCoreApplication.translate
        registerpage.setWindowTitle(_translate("registerpage", "Form"))
        self.labelkullaniciadi.setText(_translate("registerpage", "Kullanıcı Adı"))
        self.labelsifre.setText(_translate("registerpage", "Şifre"))
        self.labelmailadresi.setText(_translate("registerpage", "Mail Adresi"))
        self.pushButton_kayit.setText(_translate("registerpage", "KAYDOL"))
