# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomepage(object):
    def setupUi(self, welcomepage):
        welcomepage.setObjectName("welcomepage")
        welcomepage.resize(403, 302)
        welcomepage.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.144, y1:0.188, x2:1, y2:1, stop:0 rgba(147, 183, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(welcomepage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(24, 93, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 80, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(24, 93, 255)")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 150, 95, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("color:rgb(24, 93, 255);\n"
"background-color: rgba(153, 186, 221, 47);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setStyleSheet("color:rgb(24, 93, 255);\n"
"background-color: rgba(153, 186, 221, 47);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        welcomepage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(welcomepage)
        self.statusbar.setObjectName("statusbar")
        welcomepage.setStatusBar(self.statusbar)

        self.retranslateUi(welcomepage)
        QtCore.QMetaObject.connectSlotsByName(welcomepage)

    def retranslateUi(self, welcomepage):
        _translate = QtCore.QCoreApplication.translate
        welcomepage.setWindowTitle(_translate("welcomepage", "Library"))
        self.label.setText(_translate("welcomepage", "HOŞGELDİNİZ"))
        self.label_2.setText(_translate("welcomepage", "Giriş Yapmak İçin Kayıt Olun"))
        self.pushButton.setText(_translate("welcomepage", "GİRİŞ"))
        self.pushButton_2.setText(_translate("welcomepage", "KAYIT"))
